const fields = {
	firstName: {
	  name: 'firstName',
	  type: 'text',
	  value: '',
	  placeholder: '',
	  label: 'First name',
	  error: '',
	  required: true,
	},
	lastName: {
	  name: 'lastName',
	  type: 'text',
	  value: '',
	  placeholder: '',
	  label: 'Last name',
	  error: '',
	  required: true,
	},
	email: {
	  name: 'email',
	  type: 'email',
	  value: '',
	  placeholder: '',
	  label: 'Email Address',
	  error: '',
	  required: true,
	},
	phone: {
	  name: 'phone',
	  type: 'tel',
	  value: '',
	  placeholder: '',
	  label: '',
	  error: '',
	  required: true,
	},
	dob: {
	  name: 'dob',
	  type: 'date',
	  value: '',
	  placeholder: '',
	  label: 'Date of birth',
	  error: '',
	  required: true,
	},
	residentCountry: {
	  name: 'residentCountry',
	  type: 'password',
	  value: '',
	  placeholder: '',
	  label: 'Password',
	  error: '',
	  required: true,
	},
	residentState: {
	  name: 'password2',
	  type: 'password',
	  value: '',
	  placeholder: '',
	  label: 'Re-enter Password',
	  error: '',
	  required: true,
	},
	nigeriaPhone: {
	  name: 'nigeria',
	  type: 'text',
	  value: '',
	  placeholder: '',
	  label: 'Phone number',
	  error: '',
	  readOnly: true,
	},
  };
  
  export const initialState = {
	firstName: {
	  name: 'firstName',
	  type: 'text',
	  value: '',
	  placeholder: '',
	  label: 'First name',
	  error: '111111',
	  required: true,
	},
	lastName: {
	  name: 'lastName',
	  type: 'text',
	  value: '',
	  placeholder: '',
	  label: 'Last name',
	  error: '',
	  required: true,
	},
	email: {
	  name: 'email',
	  type: 'email',
	  value: '',
	  placeholder: '',
	  label: 'Email Address',
	  error: '',
	  required: true,
	},
	phone: {
	  name: 'phone',
	  type: 'tel',
	  value: '',
	  placeholder: '',
	  label: '',
	  error: '',
	  required: true,
	},
	refCode: {
	  name: 'refCode',
	  type: 'text',
	  value: '',
	  placeholder: '',
	  label: 'Referral code (optional)',
	  error: '',
	  required: true,
	},
	password: {
	  name: 'password',
	  type: 'password',
	  value: '',
	  placeholder: '',
	  label: 'Password',
	  error: '',
	  required: true,
	},
	password2: {
	  name: 'password2',
	  type: 'password',
	  value: '',
	  placeholder: '',
	  label: 'Re-enter Password',
	  error: '',
	  required: true,
	},
	nigeriaPhone: {
	  name: 'nigeria',
	  type: 'text',
	  value: '',
	  placeholder: '',
	  label: 'Phone number',
	  error: '',
	  readOnly: true,
	},
  };
  export default fields;
  